name: shellcheck
on:
  pull_request:
    paths:
      - .github/workflows/pr-shellcheck.yaml
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # https://github.com/marketplace/actions/shellcheck
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
